### ISSUE TITLE
Create Custom Markers For restaurants

### ISSUE THREAD

**Issue by GuidoCaldara** [twoking/2king#37]
## Expected Behavior
![image](https://user-images.githubusercontent.com/33505647/60882358-48a51900-a27a-11e9-9dc4-0a8a32b2b6a3.png)

## Steps to Reproduce the Problem (Optional [delete if not needed])

  1.
  2.
  3.

## Specifications (Optional [delete if not needed])

  - Screenshot:
  - Version:
  - Platform:
  - Subsystem:

**Comment by primaulia** [comment]
closing this issue, it's a duplicate for #27
