### ISSUE TITLE
Change the current location Marker

### ISSUE THREAD

**Issue by GuidoCaldara** [twoking/2king#38]
## Expected Behavior
![image](https://user-images.githubusercontent.com/33505647/60884715-34641a80-a280-11e9-8f92-faeda3a61e1c.png)

## Steps to Reproduce the Problem (Optional [delete if not needed])

  1.
  2.
  3.

## Specifications (Optional [delete if not needed])

  - Screenshot:
  - Version:
  - Platform:
  - Subsystem:

**Comment by primaulia** [comment]
closing this issue. it's a duplicate for #27
